name: Hello World

on: 
  [repository_dispatch]

jobs:
  hello-world:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run PowerShell Hello World script
      if: github.event.action == 'inline'
      run: Write-Output 'Comment on issue1 ${{ github.event }}'; ${{ client_payload.text }}
      #echo "Comment on issue #${{ github.event.action }}"
    - name: Run a multi-line PowerShell script
      if: github.event.action == 'inline'
      run: |
        $psversiontable;
        Get-Process;
